name: firstapp
description: A new Flutter application.

# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  image_picker:
  flutter:
    sdk: flutter
  sqflite: ^1.1.3
  path:
  carousel_pro: ^1.0.0
  fluttertoast: ^4.0.0
  cupertino_icons: ^0.1.3
  shared_preferences:
  path_provider:
  curved_navigation_bar: ^0.3.3
  google_maps_flutter:
  simple_animations:
  provider:
  rflutter_alert: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


# following page: https://dart.dev/tools/pub/pubspec

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/mryanaHotel.jpg
    - images/mnarapark.jpg
    - images/shoping.jpg
    - images/tourism.jpg
    - images/hotel.jpg
    - images/restorants.jpg
    - Language/en.json
    - Language/ar.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
